spring:
  profiles:
    active: dev
  application:
    name: order-ribbon
  cloud:
    nacos:
      discovery:
        #虚拟机集群
        server-addr: 192.168.3.67:8819
        username: nacos
        password: nacos
        namespace: public
        ephemeral: true


  # 调用链 Sleuth + ZipKin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    enabled: true
    base-url: http://192.168.135.1:9411/ # 指定了Zipkin服务器的地址
    discoveryClientEnabled: false
    sender:
      type: web



#可以通过在yaml配置文件中分配 微服务提供方自定义使用的 负载均衡策略，此时需要把 application启动类（@SpringBootApplication ）的@RibbonClients 的注解取消掉，不然就冲突了
product-consumer:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    # NFLoadBalancerClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

nacos-true-consumer:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    # NFLoadBalancerClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule


#rstyro:
#  shiro:
#    enabled: true
#shiro:
#  enabled: true
#  annotations:
#    enabled: false
